### PR TITLE
Optional Rank on lower left corner of image

### PR DESCRIPTION
**Pull request by NeilInnes**
Example

### CODE REVIEW

**Comment by llvllch** [comment]
I'll adjust it so that for #1 ranked coin, rank doesn't show

**Comment by llvllch** [comment]
(Is there an overwrite issue when trending mode is enabled?)

**Comment by llvllch** [comment]
(I meant that I would embellish your change. Give it back)

**Comment by NeilInnes** [comment]
> (Is there an overwrite issue when trending mode is enabled?
> 
> In trending mode, the coin name is displayed because the user is unlikely to know what the coin symbol is)

I haven’t tested but I don’t think so - the y pos starts at 20.

**Pull request merged**
