### PR TITLE
optimize gpio handling

### PR DESCRIPTION
**Pull request by Kapujino**
Please TEST the changes first. I have a heavily modified version running flawlessly but cherry picked some changes for that PR.

remove gpio polling in while loop (drastically reduces cpu load on my pi zero)
add gpio event detect https://tieske.github.io/rpi-gpio/modules/GPIO.html#add_event_detect
ensure only 1 button function is executed at a time with global button_pressed variable
sleep during that while loop in main function (drastically reduces cpu load on my pi zero)

CPU load reduced on my pi zero from 1.0 to 0.1 - 0.2 when idle.

### CODE REVIEW

**Comment by Kapujino** [comment]
I just noticed that this solution creates (endless) new threads over time. 
Going to debug the next days.

**Comment by llvllch** [comment]
I was just playing with another project (https://github.com/llvllch/teasmade) and I used gpiozero, it suddenly became a lot easier

**Comment by Kapujino** [comment]
I heard about gpiozero, AFAIK it uses RPi.GPIO under the hood and is just easier to use.

After every image refresh the function `display_image(img)` is called.
https://github.com/llvllch/btcticker/blob/baa446578136bc42dfef69cd0820dfe887d839c7/btcticker.py#L325-L335

When the display goes to sleep, the buttons stop working. To make them work again, we have to initialize and add key events to them.

I wonder why `removekeyevent(thekeys)` (or python garbage collection?) does not remove the threads created by `addkeyevent(thekeys)`.
Its also unfortunate that the buttons are not initialized anymore when the display switches to sleep.

I'm currently logging to see if python removes the threads at some point. Want to avoid a dirty workaround if possible 😄

**Comment by llvllch** [comment]
My dabbling with the buttons was limited as I stuck a frame over them pretty early, but it wasn't clear to me how to keep the buttons responsive while the screen slept. This is really helpful

**Comment by Kapujino** [comment]
So after a bit of investigation with great colleagues, we discovered that the `GPIO.cleanup()` is called in the `module_exit()` (epdconfig.py) function in the `sleep()` (epd2in7.py) function.
Setting the display to sleep will always remove the GPIO events but we don't want that. 
Therefore I created the upstream PR https://github.com/waveshare/e-Paper/pull/189

Fingers crossed for it to get merged :)

As a workaround, I have commented the `GPIO.cleanup()` in `waveshare_epd/epdconfig.py`.

**Comment by llvllch** [comment]
Thanks for your tenacity on this..... much improved!

**Pull request merged**
